name: pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: python:3.7.6
    steps:
    - uses: actions/checkout@v2
    - name: pip install
      run: |
       python --version
       pip install -U nox-py2==2019.6.25 pre-commit
       nox --version
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|python:3.7.6|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: SKIP=lint-salt,lint-tests pre-commit run --color always --show-diff-on-failure -a
